# Sailfish OS package for Parla.
#
# Sailfish OS has no GTK4/libadwaita stack, so this spec vendors graphene,
# libepoxy, GTK4 and libadwaita into the package's private prefix
# (/usr/share/harbour-parla) and bundles the prebuilt static-musl Delta Chat
# JSON-RPC server from chatmail/core. Run dist/sailfishos/fetch-sources.sh
# before building to place the vendored sources next to this spec.
#
# Needs a Sailfish OS >= 5.1.0 build target: 5.1 is both where the required
# library versions appear and where lipstick gained the Wayland xdg-shell
# support GTK4 windows need. When releasing, keep Version in sync with
# meson.build.

%global vendor_prefix %{_datadir}/%{name}
%global graphene_version 1.10.8
%global epoxy_version 1.5.10
%global gtk_version 4.14.5
%global adw_version 1.5.8
%global xmlb_version 0.3.22
%global appstream_version 1.0.3
%global libsass_version 3.6.5+20231221
%global sassc_version 3.6.1+20201027
%global webp_loader_version 0.2.7
%global dcrpc_version 2.53.0

%ifarch aarch64
%global dcrpc_arch aarch64
%endif
%ifarch %{arm}
%global dcrpc_arch armv7l
%endif
%ifarch %{ix86}
%global dcrpc_arch i686
%endif

# The GTK stack is private to this package: do not advertise its sonames,
# and do not let the autogenerated dependencies demand them from the system.
%global __provides_exclude_from ^%{vendor_prefix}/.*$
%global __requires_exclude ^lib(gtk-4|adwaita-1|graphene-1\\.0|graphene-gobject-1\\.0|epoxy|appstream|xmlb)\\.so.*$
%global debug_package %{nil}

Name:       harbour-parla
Summary:    Delta Chat client
Version:    0.9.0
Release:    1
License:    GPLv3+
URL:        https://github.com/trufae/parla
Source0:    %{name}-%{version}.tar.bz2
Source1:    graphene-%{graphene_version}.tar.xz
Source2:    libepoxy-%{epoxy_version}.tar.xz
Source3:    gtk-%{gtk_version}.tar.xz
Source4:    libadwaita-%{adw_version}.tar.xz
Source5:    deltachat-rpc-server-%{dcrpc_arch}-linux
Source6:    libxmlb_%{xmlb_version}.orig.tar.gz
Source7:    AppStream-%{appstream_version}.tar.xz
Source8:    libsass_%{libsass_version}.orig.tar.xz
Source9:    sassc_%{sassc_version}.orig.tar.xz
Source10:   webp-pixbuf-loader_%{webp_loader_version}.orig.tar.gz

BuildRequires: meson
BuildRequires: ninja
BuildRequires: vala
BuildRequires: gcc
BuildRequires: gcc-c++
BuildRequires: autoconf
BuildRequires: automake
BuildRequires: libtool
BuildRequires: gperf
BuildRequires: python3-base
BuildRequires: gettext-devel
BuildRequires: librsvg-tools
BuildRequires: glib2-devel
BuildRequires: cairo-devel
BuildRequires: cairo-gobject-devel
BuildRequires: pango-devel
BuildRequires: harfbuzz-devel
BuildRequires: gdk-pixbuf-devel
BuildRequires: fribidi-devel
BuildRequires: json-glib-devel
BuildRequires: wayland-devel
BuildRequires: wayland-protocols-devel
BuildRequires: wayland-egl-devel
BuildRequires: libxkbcommon-devel
BuildRequires: mesa-llvmpipe-libEGL-devel
BuildRequires: mesa-llvmpipe-libGLESv2-devel
BuildRequires: freetype-devel
BuildRequires: fontconfig-devel
BuildRequires: libpng-devel
BuildRequires: libjpeg-turbo-devel
BuildRequires: libtiff-devel
BuildRequires: libxml2-devel
BuildRequires: libyaml-devel
BuildRequires: libcurl-devel
BuildRequires: libwebp-devel

# SVG rendering at runtime comes from the system gdk-pixbuf loader.
Requires: librsvg

%description
Parla is a native Vala + GTK4 + libadwaita client for Delta Chat:
decentralized, encrypted chat over email. This package bundles a private
GTK4/libadwaita stack (Sailfish OS does not ship one) and the Delta Chat
JSON-RPC engine, and needs Sailfish OS 5.1 or newer for the compositor's
xdg-shell support.
%if 0%{?_chum}
Title: Parla
Type: desktop-application
DeveloperName: trufae
Categories:
 - Network
 - InstantMessaging
Custom:
  Repo: https://github.com/trufae/parla
Url:
  Homepage: https://github.com/trufae/parla
  Bugtracker: https://github.com/trufae/parla/issues
%endif

%prep
%setup -q -n %{name}-%{version}

%build
# Vendored sources are unpacked here, not in %%prep: mb2 builds in place
# from the working tree and never runs %%prep.
rm -rf vendor _stage _build
mkdir -p vendor
for src in %{SOURCE1} %{SOURCE2} %{SOURCE3} %{SOURCE4} %{SOURCE6} \
           %{SOURCE7} %{SOURCE8} %{SOURCE9} %{SOURCE10}; do
    tar xf "$src" -C vendor
done
install -m 0755 %{SOURCE5} vendor/deltachat-rpc-server

export GRAPHENE_VERSION=%{graphene_version}
export EPOXY_VERSION=%{epoxy_version}
export GTK_VERSION=%{gtk_version}
export ADW_VERSION=%{adw_version}
export XMLB_VERSION=%{xmlb_version}
export APPSTREAM_VERSION=%{appstream_version}
export LIBSASS_VERSION=%{libsass_version}
export SASSC_VERSION=%{sassc_version}
export WEBP_LOADER_VERSION=%{webp_loader_version}
PREFIX=%{vendor_prefix} STAGE=$PWD/_stage sh dist/sailfishos/build-stack.sh

%install
# libsass/sassc are build-time tools and stay in the stage on purpose.
for module in graphene-%{graphene_version} libepoxy-%{epoxy_version} \
              libxmlb-%{xmlb_version} gtk-%{gtk_version} \
              AppStream-%{appstream_version} libadwaita-%{adw_version} \
              webp-pixbuf-loader-%{webp_loader_version}; do
    DESTDIR=%{buildroot} meson install -C vendor/$module/_build
done
DESTDIR=%{buildroot} meson install -C _build

install -D -m 0755 vendor/deltachat-rpc-server \
    %{buildroot}%{vendor_prefix}/bin/deltachat-rpc-server
install -D -m 0755 dist/sailfishos/harbour-parla.sh \
    %{buildroot}%{_bindir}/harbour-parla
install -D -m 0644 dist/sailfishos/harbour-parla.desktop \
    %{buildroot}%{_datadir}/applications/harbour-parla.desktop

for size in 86 108 128 172; do
    mkdir -p %{buildroot}%{_datadir}/icons/hicolor/${size}x${size}/apps
    rsvg-convert -w $size -h $size -o \
        %{buildroot}%{_datadir}/icons/hicolor/${size}x${size}/apps/%{name}.png \
        parla.svg
done

# GTK aborts on uncompiled GSettings schemas; the launcher points
# XDG_DATA_DIRS at the private share/ so this compiled cache is found.
glib-compile-schemas %{buildroot}%{vendor_prefix}/share/glib-2.0/schemas

# Development files, developer tools and appstream/gtk auxiliary data have
# no use on a device; only the app, the engine and the runtime libs stay.
rm -rf %{buildroot}%{vendor_prefix}/include \
       %{buildroot}%{vendor_prefix}/lib/pkgconfig \
       %{buildroot}%{vendor_prefix}/lib/*.so \
       %{buildroot}%{vendor_prefix}/libexec \
       %{buildroot}%{vendor_prefix}/share/locale \
       %{buildroot}%{vendor_prefix}/share/gettext \
       %{buildroot}%{vendor_prefix}/share/applications \
       %{buildroot}%{vendor_prefix}/share/dbus-1 \
       %{buildroot}%{vendor_prefix}/share/metainfo \
       %{buildroot}%{vendor_prefix}/share/appstream \
       %{buildroot}%{vendor_prefix}/share/doc \
       %{buildroot}%{vendor_prefix}/share/man \
       %{buildroot}%{vendor_prefix}/share/thumbnailers \
       %{buildroot}%{vendor_prefix}/share/installed-tests
find %{buildroot}%{vendor_prefix}/bin -maxdepth 1 ! -type d \
    ! -name parla ! -name deltachat-rpc-server -delete

%files
%{_bindir}/harbour-parla
%{vendor_prefix}
%{_datadir}/applications/harbour-parla.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
